/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Panels;

import conexion.Conexion;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marcelo
 */
public class Clientes extends javax.swing.JPanel {

    private static Clientes clientes = null;
    
    public Clientes() {
        initComponents();       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosCliente = new javax.swing.JPanel();
        barrio = new javax.swing.JTextField();
        calle = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        trabajo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        buscarTodos = new javax.swing.JTextField();
        buscarParcela = new javax.swing.JTextField();
        buscarManzana = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buscarManzana1 = new javax.swing.JTextField();
        eliminarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        datosReferencia = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        apellido_referencia = new javax.swing.JTextField();
        nombre_referencia = new javax.swing.JTextField();
        parentesco = new javax.swing.JTextField();
        telefono_referencia = new javax.swing.JTextField();
        detalleBtn = new javax.swing.JButton();
        asignarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable()
        {
            public Component prepareRenderer(TableCellRenderer renderer, int rowIndex, int vColIndex) {
                Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
                //---Pinto de rosado si el cliente no tiene propiedad asignada---//
                if(tablaCliente.getValueAt(rowIndex, 11) == null){
                    c.setBackground(Color.PINK);
                }
                //-----Pinto de rojo si el cliente esta dado de baja--//
                if(tablaCliente.getValueAt(rowIndex, 10)!=null){
                    if(tablaCliente.getValueAt(rowIndex, 10).equals("1")){
                        c.setBackground(Color.RED);
                    }}
                    if (isCellSelected(rowIndex, vColIndex)) {
                        c.setBackground(Color.yellow);
                    }
                    return c;
                }
            }
            ;
            agregarPropietario = new javax.swing.JButton();
            cambiarPropietario = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            jLabel14 = new javax.swing.JLabel();
            jLabel15 = new javax.swing.JLabel();
            fch_actualizacion = new javax.swing.JLabel();
            bolsa_cemento = new javax.swing.JTextField();
            advertencia = new javax.swing.JLabel();
            jLabel16 = new javax.swing.JLabel();
            jPanel3 = new javax.swing.JPanel();
            jLabel18 = new javax.swing.JLabel();
            bajaBtn = new javax.swing.JButton();
            jPanel4 = new javax.swing.JPanel();
            jLabel19 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            comboApellido = new javax.swing.JComboBox<>();
            comboNombre = new javax.swing.JComboBox<>();
            jLabel17 = new javax.swing.JLabel();
            jLabel20 = new javax.swing.JLabel();
            mostrarTodos = new javax.swing.JButton();

            datosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12))); // NOI18N

            barrio.setEditable(false);
            barrio.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    barrioActionPerformed(evt);
                }
            });

            calle.setEditable(false);
            calle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    calleActionPerformed(evt);
                }
            });

            numero.setEditable(false);
            numero.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    numeroActionPerformed(evt);
                }
            });

            trabajo.setEditable(false);
            trabajo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    trabajoActionPerformed(evt);
                }
            });

            jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel1.setText("Calle");

            jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel3.setText("Número");

            jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel2.setText("Barrio");

            jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel4.setText("Lugar de trabajo");

            javax.swing.GroupLayout datosClienteLayout = new javax.swing.GroupLayout(datosCliente);
            datosCliente.setLayout(datosClienteLayout);
            datosClienteLayout.setHorizontalGroup(
                datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datosClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datosClienteLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosClienteLayout.createSequentialGroup()
                            .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(trabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(calle)
                                .addComponent(numero)))))
            );
            datosClienteLayout.setVerticalGroup(
                datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datosClienteLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(datosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
            );

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 3, 12))); // NOI18N

            buscarTodos.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    buscarTodosKeyReleased(evt);
                }
            });

            buscarParcela.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    buscarParcelaKeyReleased(evt);
                }
            });

            buscarManzana.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    buscarManzanaActionPerformed(evt);
                }
            });
            buscarManzana.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    buscarManzanaKeyReleased(evt);
                }
            });

            jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel6.setText("Parcela/Dpto");

            jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel7.setText("Manzana/Piso");

            jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel8.setText("Apellido/Nombre/Documento");

            jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel13.setText("Barrio/Torre");

            buscarManzana1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    buscarManzana1KeyReleased(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel13)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buscarParcela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(buscarManzana1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(3, 3, 3)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscarManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(buscarTodos))
                    .addContainerGap(52, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarManzana1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(buscarManzana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(24, Short.MAX_VALUE))
            );

            eliminarBtn.setText("Eliminar propietario");
            eliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    eliminarBtnMouseClicked(evt);
                }
            });

            agregarBtn.setText("Nuevo propietario");
            agregarBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    agregarBtnActionPerformed(evt);
                }
            });

            editarBtn.setText("Editar propietario");

            datosReferencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos referencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12))); // NOI18N

            jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel9.setText("Apellido/s");

            jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel10.setText("Nombre/s");

            jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel11.setText("Teléfono");

            jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
            jLabel12.setText("Parentesco");

            apellido_referencia.setEditable(false);

            nombre_referencia.setEditable(false);

            parentesco.setEditable(false);

            telefono_referencia.setEditable(false);

            javax.swing.GroupLayout datosReferenciaLayout = new javax.swing.GroupLayout(datosReferencia);
            datosReferencia.setLayout(datosReferenciaLayout);
            datosReferenciaLayout.setHorizontalGroup(
                datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datosReferenciaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(datosReferenciaLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(48, 48, 48)
                            .addComponent(parentesco, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGroup(datosReferenciaLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(56, 56, 56)
                            .addComponent(apellido_referencia))
                        .addGroup(datosReferenciaLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(58, 58, 58)
                            .addComponent(nombre_referencia))
                        .addGroup(datosReferenciaLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(65, 65, 65)
                            .addComponent(telefono_referencia))))
            );
            datosReferenciaLayout.setVerticalGroup(
                datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(datosReferenciaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(apellido_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(nombre_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(telefono_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(datosReferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            detalleBtn.setText("Detalle pago");

            asignarBtn.setText("Asignar propiedad");

            JTableHeader header = tablaCliente.getTableHeader();
            Color micolor = new Color(36,47,65);
            header.setForeground(Color.white);
            header.setBackground(micolor);
            tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Apellido/s", "Nombre/s", "Documento", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Barrio", "Manzana", "Parcela", "Observacion", "actualizar_cto", "cumpleaños", "Title 23"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane2.setViewportView(tablaCliente);
            if (tablaCliente.getColumnModel().getColumnCount() > 0) {
                tablaCliente.getColumnModel().getColumn(2).setResizable(false);
                tablaCliente.getColumnModel().getColumn(2).setPreferredWidth(1);
                tablaCliente.getColumnModel().getColumn(3).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(3).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(3).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(4).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(4).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(4).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(5).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(5).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(5).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(6).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(6).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(6).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(7).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(7).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(7).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(8).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(8).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(8).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(9).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(9).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(9).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(10).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(10).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(10).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(11).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(11).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(11).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(12).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(12).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(12).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(13).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(13).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(13).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(14).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(14).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(14).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(15).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(15).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(15).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(16).setPreferredWidth(1);
                tablaCliente.getColumnModel().getColumn(17).setPreferredWidth(1);
                tablaCliente.getColumnModel().getColumn(18).setPreferredWidth(1);
                tablaCliente.getColumnModel().getColumn(20).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(20).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(20).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(21).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(21).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(21).setMaxWidth(0);
                tablaCliente.getColumnModel().getColumn(22).setMinWidth(0);
                tablaCliente.getColumnModel().getColumn(22).setPreferredWidth(0);
                tablaCliente.getColumnModel().getColumn(22).setMaxWidth(0);
            }

            agregarPropietario.setText("Agregar propietario");

            cambiarPropietario.setText("Cambiar propietario");

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bolsa de cemento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 12))); // NOI18N

            jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel14.setText("Fecha actualizacion:");

            jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel15.setText("Precio:");

            fch_actualizacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

            bolsa_cemento.setToolTipText("Ingrese el nuevo valor y presione ENTER");

            advertencia.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
            advertencia.setForeground(new java.awt.Color(255, 0, 0));

            jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel16.setText("$");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fch_actualizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(bolsa_cemento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 104, Short.MAX_VALUE)))))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fch_actualizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(bolsa_cemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel3.setBackground(java.awt.Color.pink);
            jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jPanel3.setForeground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 13, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 12, Short.MAX_VALUE)
            );

            jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
            jLabel18.setText("Sin propiedad");

            bajaBtn.setText("Dar de baja");
            bajaBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bajaBtnActionPerformed(evt);
                }
            });

            jPanel4.setBackground(java.awt.Color.red);
            jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jPanel4.setForeground(new java.awt.Color(255, 255, 255));

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 13, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 13, Short.MAX_VALUE)
            );

            jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
            jLabel19.setText("Dado de baja");

            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Propietario"));

            comboApellido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

            comboNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

            jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel17.setText("Apellido");

            jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
            jLabel20.setText("Nombre");

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comboNombre, 0, 252, Short.MAX_VALUE)
                        .addComponent(comboApellido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addGap(0, 9, Short.MAX_VALUE))
            );

            mostrarTodos.setText("Mostrar todos");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(mostrarTodos))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(296, 296, 296)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel19))))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(agregarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eliminarBtn)
                                .addComponent(bajaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(detalleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(asignarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(datosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(agregarPropietario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cambiarPropietario)))
                                .addComponent(datosReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap())))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mostrarTodos)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(agregarBtn)
                                .addComponent(eliminarBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editarBtn)
                                .addComponent(bajaBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(asignarBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(detalleBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(agregarPropietario)
                                .addComponent(cambiarPropietario))
                            .addGap(2, 2, 2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(datosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(datosReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            datosCliente.getAccessibleContext().setAccessibleName("");
        }// </editor-fold>//GEN-END:initComponents

    private void barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrioActionPerformed

    private void calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trabajoActionPerformed

    private void buscarTodosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTodosKeyReleased
        String query=buscarTodos.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_buscarTodosKeyReleased

    private void filter(String query){
         DefaultTableModel table = (DefaultTableModel) tablaCliente.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (table);
         tablaCliente.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }
    
    private void eliminarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseClicked
         int row = tablaCliente.getSelectedRowCount();
        if(row==0){
            JOptionPane.showMessageDialog(null, "Seleccione un cliente de la lista", "Atención",JOptionPane.WARNING_MESSAGE); 
        }
    }//GEN-LAST:event_eliminarBtnMouseClicked

    private void buscarParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarParcelaKeyReleased
         String query=buscarParcela.getText().toLowerCase();
        filtroParcela(query);
    }//GEN-LAST:event_buscarParcelaKeyReleased
  
    private void buscarManzanaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarManzanaKeyReleased
         String query=buscarManzana.getText().toLowerCase();
        filtroManzana(query);
    }//GEN-LAST:event_buscarManzanaKeyReleased

    private void barrio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrio1ActionPerformed

    private void buscarManzana1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarManzana1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarManzana1KeyReleased

    private void buscarManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarManzanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarManzanaActionPerformed

    private void bajaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarBtnActionPerformed
    private void filtroParcela(String query){
         DefaultTableModel table = (DefaultTableModel) tablaCliente.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (table);
         tablaCliente.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)" + query,16));
    }
    private void filtroManzana(String query){
         DefaultTableModel table = (DefaultTableModel) tablaCliente.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (table);
         tablaCliente.setRowSorter(tr);
         tr.setRowFilter(RowFilter.regexFilter("(?i)" + query,15));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel advertencia;
    public javax.swing.JButton agregarBtn;
    public javax.swing.JButton agregarPropietario;
    public javax.swing.JTextField apellido_referencia;
    public javax.swing.JButton asignarBtn;
    public javax.swing.JButton bajaBtn;
    public javax.swing.JTextField barrio;
    public javax.swing.JTextField bolsa_cemento;
    public javax.swing.JTextField buscarManzana;
    public javax.swing.JTextField buscarManzana1;
    public javax.swing.JTextField buscarParcela;
    public javax.swing.JTextField buscarTodos;
    public javax.swing.JTextField calle;
    public javax.swing.JButton cambiarPropietario;
    public javax.swing.JComboBox<String> comboApellido;
    public javax.swing.JComboBox<String> comboNombre;
    public javax.swing.JPanel datosCliente;
    public javax.swing.JPanel datosReferencia;
    public javax.swing.JButton detalleBtn;
    public javax.swing.JButton editarBtn;
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JLabel fch_actualizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton mostrarTodos;
    public javax.swing.JTextField nombre_referencia;
    public javax.swing.JTextField numero;
    public javax.swing.JTextField parentesco;
    public javax.swing.JTable tablaCliente;
    public javax.swing.JTextField telefono_referencia;
    public javax.swing.JTextField trabajo;
    // End of variables declaration//GEN-END:variables
}