/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Panels;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import conexion.Conexion;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcelo
 */
public class DetallePago extends javax.swing.JPanel {

    private String idControl;
    private Object [] detalles;
    private String nombre, apellido;
    public static final String IMG = "src/Imagenes/logo_reporte.png";
    
    public DetallePago() {
        initComponents();
    }

    public DetallePago(String idControl,String apellido, String nombre) {
        this.idControl = idControl;   
        initComponents();
        apellidoLabel.setText(apellido);
        nombreLabel.setText(nombre);
        cargarDetalle();
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void cargarDetalle(){
       Conexion conexion = new Conexion();
        try {
        conexion.rs = conexion.st.executeQuery("select * from detalle_control where idControl ='" + idControl +"'" );                    
      
            while(conexion.rs.next()){
        
                String fecha = conexion.rs.getString(2);
                String detalle = conexion.rs.getString(3);
                String cuota = conexion.rs.getString(4);
                String gastos = conexion.rs.getString(5);  
                detalles = new Object[] {fecha, detalle, cuota, gastos};
                DefaultTableModel model = (DefaultTableModel) detallePago.getModel();
                model.addRow(detalles);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detallePago = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        apellidoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1112, 479));

        detallePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Detalle ", "Cuota pura", "Gastos adminstrativos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(detallePago);

        jButton1.setText("Volver");

        jButton2.setText("Generar recibo");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        apellidoLabel.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N

        nombreLabel.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N

        jButton3.setText("Agregar pago");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(apellidoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            Document document= new Document(PageSize.A4);
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("report.pdf"));
               document.open();
            Image image = Image.getInstance(IMG); 
            PdfPTable table = new PdfPTable(2); // 3 columns.
            table.setHorizontalAlignment(Element.ALIGN_RIGHT); 
            PdfPCell cell1 = new PdfPCell();
            PdfPCell cell3 = new PdfPCell(new Paragraph("Recibo por orden y cuenta de terceros"));
            cell1.setBorder(Rectangle.RIGHT);
            cell3.setVerticalAlignment(Element.ALIGN_MIDDLE);
            table.addCell(cell1);
            table.addCell(cell3);
            table.setSpacingAfter(20);
            document.add(table);    
            Paragraph para = new Paragraph("Numero: ...........");
            Paragraph cuit = new Paragraph("CUIT: 23-07431900-9");
             Paragraph ingBrutos = new Paragraph("Ing Brutos: 01-23-07431900-9");
            Paragraph inicAct = new Paragraph("Inic. Act.: 01-08-2015");       
            para.setAlignment(Paragraph.ALIGN_RIGHT);
            cuit.setAlignment(Paragraph.ALIGN_RIGHT);
            ingBrutos.setAlignment(Paragraph.ALIGN_RIGHT);
            inicAct.setAlignment(Paragraph.ALIGN_RIGHT);
            document.add(new Chunk(image, 0, -60f));
            document.add(para);
            document.add(cuit);
            document.add(ingBrutos);
            document.add(inicAct);
            document.add( Chunk.NEWLINE );
            PdfPTable table2 = new PdfPTable(1);
            table2.setWidthPercentage(100);
            PdfPCell cell4 = new PdfPCell(new Paragraph("Propietario:......."));
            PdfPCell cell5 = new PdfPCell(new Paragraph("Nombre comprador:....."));
            cell4.disableBorderSide(2);
            cell5.disableBorderSide(1);
            table2.addCell(cell4);
             table2.addCell(cell5);
             document.add(table2);
            PdfPTable checkbox = new PdfPTable(8);
            checkbox.setTotalWidth(new float[]{ 3,1,3,1,3,1,3,1});
            checkbox.setWidthPercentage(100);
            Font f=new Font(FontFamily.TIMES_ROMAN,10.0f,0,null);
            PdfPCell check1 = new PdfPCell(new Paragraph("Iva Resp. Inscripto",f));
            PdfPCell check2 = new PdfPCell(new Paragraph(""));
            check1.disableBorderSide(4);
            check1.disableBorderSide(3);
            checkbox.addCell(check1);
            checkbox.addCell(check2);
            PdfPCell check3 = new PdfPCell(new Paragraph("Resp. No Inscripto",f));
            PdfPCell check4 = new PdfPCell(new Paragraph(""));
            check3.disableBorderSide(4);
            check3.disableBorderSide(3);
            checkbox.addCell(check3);
            checkbox.addCell(check4);
            PdfPCell check5 = new PdfPCell(new Paragraph("Monotributo",f));
            PdfPCell check6 = new PdfPCell(new Paragraph(""));
            check5.disableBorderSide(4);
            check5.disableBorderSide(3);
            checkbox.addCell(check5);
            checkbox.addCell(check6);
            PdfPCell check7 = new PdfPCell(new Paragraph("Exento",f));
            PdfPCell check8 = new PdfPCell(new Paragraph(""));
            check7.disableBorderSide(4);
            check7.disableBorderSide(3);
            checkbox.addCell(check7);
            checkbox.addCell(check8);
            document.add(checkbox);
            document.close();
            }catch (DocumentException ex) {
            Logger.getLogger(DetallePago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DetallePago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DetallePago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        AltaPago ap = new AltaPago((JFrame)this.getRootPane().getParent(), true);
       ap.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    class ParagraphBorder extends PdfPageEventHelper {
    public boolean active = false;
    public void setActive(boolean active) {
        this.active = active;
    }

    public float offset = 5;
    public float startPosition;

    @Override
    public void onParagraph(PdfWriter writer, Document document, float paragraphPosition) {
        this.startPosition = paragraphPosition;
    }

    @Override
    public void onParagraphEnd(PdfWriter writer, Document document, float paragraphPosition) {
        if (active) {
            PdfContentByte cb = writer.getDirectContentUnder();
            cb.rectangle(document.left(), paragraphPosition - offset,
                document.right() - document.left(), startPosition - paragraphPosition);
            cb.stroke();
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JTable detallePago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreLabel;
    // End of variables declaration//GEN-END:variables
}
